fix : docker permission in pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,6 +53,15 @@ jobs:
         username: ${{ env.EC2_USER }}
         key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
         script: |
+            # Ensure Docker is installed
+            if ! command -v docker &> /dev/null; then
+                echo "Docker is not installed. Installing..."
+                sudo apt-get update
+                sudo apt-get install -y docker.io
+                sudo systemctl start docker
+                sudo systemctl enable docker
+            fi
+            
             # Create .env file with all necessary environment variables
             cat > /home/${{ env.EC2_USER }}/app.env << EOL
             POSTGRES_URL=${{ secrets.POSTGRES_URL }}
@@ -79,7 +88,20 @@ jobs:
               -p 3000:3000 \
               --env-file /home/${{ env.EC2_USER }}/app.env \
               ${{ env.IMAGE_NAME }}:latest
-      
+
+            # Wait for the container to start
+            sleep 10  # Adjust as needed for your application
+            
+            # Check if the container is running
+            if [ "$(docker ps -q -f name=databases-performance-test)" ]; then
+                echo "Container is running."
+            else
+                echo "Failed to start the container."
+                exit 1
+            fi
+
+            # Optional: Clean up environment file after use
+            rm /home/${{ env.EC2_USER }}/app.env
+            
             # Optional: Prune old docker images to save space
             docker image prune -f
-      
